const infoResponse = [
  {
    id: 1001,
    aisle: "Milk, Eggs, Other Dairy",
    image: "butter-sliced.jpg",
    consistency: "solid",
    name: "butter",
    nameClean: "butter",
    original: "½ Tbsp Smart Balance butter",
    originalString: "½ Tbsp Smart Balance butter",
    originalName: "Smart Balance butter",
    amount: 0.5,
    unit: "Tbsp",
    meta: [],
    metaInformation: [],
    measures: {
      us: {
        amount: 0.5,
        unitShort: "Tbsps",
        unitLong: "Tbsps",
      },
      metric: {
        amount: 0.5,
        unitShort: "Tbsps",
        unitLong: "Tbsps",
      },
    },
  },
  {
    id: 18363,
    aisle: "Bakery/Bread;Pasta and Rice;Ethnic Foods",
    image: "corn-tortillas.png",
    consistency: "solid",
    name: "corn tortillas",
    nameClean: "white corn tortilla",
    original: "4 corn tortillas",
    originalString: "4 corn tortillas",
    originalName: "corn tortillas",
    amount: 4.0,
    unit: "",
    meta: [],
    metaInformation: [],
    measures: {
      us: {
        amount: 4.0,
        unitShort: "",
        unitLong: "",
      },
      metric: {
        amount: 4.0,
        unitShort: "",
        unitLong: "",
      },
    },
  },
  {
    id: 1123,
    aisle: "Milk, Eggs, Other Dairy",
    image: "egg.png",
    consistency: "solid",
    name: "eggs",
    nameClean: "egg",
    original: "3 large eggs",
    originalString: "3 large eggs",
    originalName: "eggs",
    amount: 3.0,
    unit: "large",
    meta: [],
    metaInformation: [],
    measures: {
      us: {
        amount: 3.0,
        unitShort: "large",
        unitLong: "larges",
      },
      metric: {
        amount: 3.0,
        unitShort: "large",
        unitLong: "larges",
      },
    },
  },
  {
    id: 10011355,
    aisle: "Produce",
    image: "red-potatoes.jpg",
    consistency: "solid",
    name: "red potato",
    nameClean: "red potato",
    original: "1 small red potato",
    originalString: "1 small red potato",
    originalName: "red potato",
    amount: 1.0,
    unit: "small",
    meta: ["red"],
    metaInformation: ["red"],
    measures: {
      us: {
        amount: 1.0,
        unitShort: "small",
        unitLong: "small",
      },
      metric: {
        amount: 1.0,
        unitShort: "small",
        unitLong: "small",
      },
    },
  },
  {
    id: 1102047,
    aisle: "Spices and Seasonings",
    image: "salt-and-pepper.jpg",
    consistency: "solid",
    name: "Salt & Pepper",
    nameClean: "salt and pepper",
    original: "salt & pepper",
    originalString: "salt & pepper",
    originalName: "salt & pepper",
    amount: 2.0,
    unit: "servings",
    meta: [],
    metaInformation: [],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "servings",
        unitLong: "servings",
      },
      metric: {
        amount: 2.0,
        unitShort: "servings",
        unitLong: "servings",
      },
    },
  },
  {
    id: 1001009,
    aisle: "Cheese",
    image: "shredded-cheddar.jpg",
    consistency: "solid",
    name: "shredded cheddar cheese",
    nameClean: "shredded cheddar cheese",
    original: "2 tbsp shredded cheddar cheese",
    originalString: "2 tbsp shredded cheddar cheese",
    originalName: "shredded cheddar cheese",
    amount: 2.0,
    unit: "tbsp",
    meta: ["shredded"],
    metaInformation: ["shredded"],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "Tbsps",
        unitLong: "Tbsps",
      },
      metric: {
        amount: 2.0,
        unitShort: "Tbsps",
        unitLong: "Tbsps",
      },
    },
  },
];

export default infoResponse;
