export const rawData = {
  vegetarian: true,
  vegan: false,
  glutenFree: true,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 12,
  gaps: "no",
  lowFodmap: false,
  aggregateLikes: 1,
  spoonacularScore: 33,
  healthScore: 4,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 121.34,
  extendedIngredients: [
    {
      id: 19334,
      aisle: "Baking",
      image: "light-brown-sugar.jpg",
      consistency: "solid",
      name: "brown sugar",
      nameClean: "golden brown sugar",
      original: "1/4 cup brown sugar",
      originalString: "1/4 cup brown sugar",
      originalName: "brown sugar",
      amount: 0.25,
      unit: "cup",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 59.147,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 2010,
      aisle: "Spices and Seasonings",
      image: "cinnamon.jpg",
      consistency: "solid",
      name: "cinnamon",
      nameClean: "cinnamon",
      original: "1/2 teaspoon cinnamon",
      originalString: "1/2 teaspoon cinnamon",
      originalName: "cinnamon",
      amount: 0.5,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 19304,
      aisle: "Baking",
      image: "molasses.jpg",
      consistency: "solid",
      name: "dark molasses",
      nameClean: "molasses",
      original: "1/4 cup dark molasses",
      originalString: "1/4 cup dark molasses",
      originalName: "dark molasses",
      amount: 0.25,
      unit: "cup",
      meta: ["dark"],
      metaInformation: ["dark"],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 59.147,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 1123,
      aisle: "Milk, Eggs, Other Dairy",
      image: "egg.png",
      consistency: "solid",
      name: "eggs",
      nameClean: "egg",
      original: "4 • eggs",
      originalString: "4 • eggs",
      originalName: "eggs",
      amount: 4,
      unit: "",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 4,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 4,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 9297,
      aisle: "Dried Fruits;Produce;Baking",
      image: "golden-raisins.jpg",
      consistency: "solid",
      name: "golden raisins",
      nameClean: "golden raisins",
      original: "1/4 pound golden raisins",
      originalString: "1/4 pound golden raisins",
      originalName: "golden raisins",
      amount: 0.25,
      unit: "pound",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "lb",
          unitLong: "pounds",
        },
        metric: {
          amount: 113.398,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 2021,
      aisle: "Spices and Seasonings",
      image: "ginger.png",
      consistency: "solid",
      name: "ground ginger",
      nameClean: "ginger powder",
      original: "1/2 tablespoon ground ginger",
      originalString: "1/2 tablespoon ground ginger",
      originalName: "ground ginger",
      amount: 0.5,
      unit: "tablespoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 0.5,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 93814,
      aisle: "Milk, Eggs, Other Dairy",
      image: "whipped-cream.jpg",
      consistency: "solid",
      name: "lightly sweetened whipped cream",
      nameClean: "lightly sweetened whipped cream",
      original: "Lightly-sweetened whipped cream or",
      originalString: "Lightly-sweetened whipped cream or",
      originalName: "Lightly-sweetened whipped cream or",
      amount: 6,
      unit: "servings",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 6,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 6,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 19911,
      aisle: "Cereal",
      image: "maple-syrup.png",
      consistency: "liquid",
      name: "maple syrup",
      nameClean: "maple syrup",
      original: "3 tablespoons maple syrup",
      originalString: "3 tablespoons maple syrup",
      originalName: "maple syrup",
      amount: 3,
      unit: "tablespoons",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 3,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 3,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 1077,
      aisle: "Milk, Eggs, Other Dairy",
      image: "milk.png",
      consistency: "liquid",
      name: "milk",
      nameClean: "milk",
      original: "1 tablespoon • milk",
      originalString: "1 tablespoon • milk",
      originalName: "milk",
      amount: 1,
      unit: "tablespoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 2025,
      aisle: "Spices and Seasonings",
      image: "ground-nutmeg.jpg",
      consistency: "solid",
      name: "nutmeg",
      nameClean: "nutmeg",
      original: "3/4 teaspoon nutmeg",
      originalString: "3/4 teaspoon nutmeg",
      originalName: "nutmeg",
      amount: 0.75,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.75,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.75,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 8121,
      aisle: "Cereal",
      image: "porridge-or-cream-of-wheat.png",
      consistency: "solid",
      name: "oatmeal",
      nameClean: "cooked rolled oats",
      original: "2 cups old-fashioned oatmeal",
      originalString: "2 cups old-fashioned oatmeal",
      originalName: "old-fashioned oatmeal",
      amount: 2,
      unit: "cups",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 2,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 473.176,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 2047,
      aisle: "Spices and Seasonings",
      image: "salt.jpg",
      consistency: "solid",
      name: "salt",
      nameClean: "salt",
      original: "1/2 teaspoon Salt",
      originalString: "1/2 teaspoon Salt",
      originalName: "Salt",
      amount: 0.5,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1119,
      aisle: "Milk, Eggs, Other Dairy",
      image: "vanilla-yogurt.png",
      consistency: "liquid",
      name: "vanilla yogurt",
      nameClean: "vanilla yogurt",
      original: "vanilla yogurt for accompaniment",
      originalString: "vanilla yogurt for accompaniment",
      originalName: "vanilla yogurt for accompaniment",
      amount: 6,
      unit: "servings",
      meta: ["for accompaniment"],
      metaInformation: ["for accompaniment"],
      measures: {
        us: {
          amount: 6,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 6,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 12155,
      aisle: "Nuts;Baking",
      image: "walnuts.jpg",
      consistency: "solid",
      name: "walnuts",
      nameClean: "walnuts",
      original: "1/4 cup chopped walnuts",
      originalString: "1/4 cup chopped walnuts",
      originalName: "chopped walnuts",
      amount: 0.25,
      unit: "cup",
      meta: ["chopped"],
      metaInformation: ["chopped"],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 59.147,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 14412,
      aisle: "Beverages",
      image: "water.png",
      consistency: "liquid",
      name: "water",
      nameClean: "water",
      original: "2 tablespoons water",
      originalString: "2 tablespoons water",
      originalName: "water",
      amount: 2,
      unit: "tablespoons",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 2,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
  ],
  id: 636062,
  title: "Breakfast Porridge",
  readyInMinutes: 45,
  servings: 6,
  sourceUrl: "http://www.foodista.com/recipe/8Y66RK4W/breakfast-porridge",
  image: "https://spoonacular.com/recipeImages/636062-556x370.jpg",
  imageType: "jpg",
  summary:
    'Breakfast Porridge might be just the morn meal you are searching for. One serving contains <b>346 calories</b>, <b>8g of protein</b>, and <b>13g of fat</b>. This gluten free and vegetarian recipe serves 6 and costs <b>$1.21 per serving</b>. This recipe from Foodista has 1 fans. Head to the store and pick up walnuts, old-fashioned oatmeal, maple syrup, and a few other things to make it today. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 35%</b>. This score is not so great. Try <a href="https://spoonacular.com/recipes/millet-breakfast-porridge-482347">Millet Breakfast Porridge</a>, <a href="https://spoonacular.com/recipes/breakfast-bulgur-porridge-201853">Breakfast Bulgur Porridge</a>, and <a href="https://spoonacular.com/recipes/whole-grain-breakfast-porridge-287777">Whole-Grain Breakfast Porridge</a> for similar recipes.',
  cuisines: [],
  dishTypes: ["morning meal", "brunch", "breakfast"],
  diets: ["gluten free", "lacto ovo vegetarian"],
  occasions: [],
  winePairing: {},
  instructions:
    "<ol><li>Heat water and salt until boiling. Add oatmeal and cook for 5 minutes. Cool.</li><li>Combine next 10 ingredients and add to oatmeal. Pour into a greased 9-inch square baking pan and bake, uncovered, in preheated 350 degree oven for 2 hours.</li><li>Serve hot topped with a dollop of whipped cream or vanilla yogurt.</li><li>This recipe yields 6 servings.</li></ol>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Heat water and salt until boiling.",
          ingredients: [
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
            {
              id: 2047,
              name: "salt",
              localizedName: "salt",
              image: "salt.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 2,
          step: "Add oatmeal and cook for 5 minutes. Cool.",
          ingredients: [
            {
              id: 8121,
              name: "oatmeal",
              localizedName: "oatmeal",
              image: "rolled-oats.jpg",
            },
          ],
          equipment: [],
          length: {
            number: 5,
            unit: "minutes",
          },
        },
        {
          number: 3,
          step: "Combine next 10 ingredients and add to oatmeal.",
          ingredients: [
            {
              id: 8121,
              name: "oatmeal",
              localizedName: "oatmeal",
              image: "rolled-oats.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 4,
          step: "Pour into a greased 9-inch square baking pan and bake, uncovered, in preheated 350 degree oven for 2 hours.",
          ingredients: [],
          equipment: [
            {
              id: 404646,
              name: "baking pan",
              localizedName: "baking pan",
              image: "roasting-pan.jpg",
            },
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "oven.jpg",
            },
          ],
          length: {
            number: 120,
            unit: "minutes",
          },
        },
        {
          number: 5,
          step: "Serve hot topped with a dollop of whipped cream or vanilla yogurt.This recipe yields 6 servings.",
          ingredients: [
            {
              id: 1119,
              name: "vanilla yogurt",
              localizedName: "vanilla yogurt",
              image: "vanilla-yogurt.png",
            },
            {
              id: 1054,
              name: "whipped cream",
              localizedName: "whipped cream",
              image: "whipped-cream.jpg",
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl: "https://spoonacular.com/breakfast-porridge-636062",
};
